# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "font_awesome-sass-rails"
  s.version = "2.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2012-11-26"
  s.description = "Use Font Awesome in your Rails app :)"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Changelog.txt",
    "FontAwesomeMore-Vectors.pdf",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "font_awesome-sass-rails.gemspec",
    "lib/font_awesome-sass-rails.rb",
    "lib/font_awesome-sass/engine.rb",
    "lib/font_awesome-sass/version.rb",
    "lib/font_awesome-sass/view_helper.rb",
    "spec/font_awesome_sass/view_helper_spec.rb",
    "spec/spec_helper.rb",
    "vendor/assets/fonts/FontAwesome.ttf",
    "vendor/assets/fonts/fontawesome-webfont.eot",
    "vendor/assets/fonts/fontawesome-webfont.svg",
    "vendor/assets/fonts/fontawesome-webfont.ttf",
    "vendor/assets/fonts/fontawesome-webfont.woff",
    "vendor/assets/stylesheets/font-awesome-ie7.css",
    "vendor/assets/stylesheets/font-awesome-less.less.erb",
    "vendor/assets/stylesheets/font-awesome-sass.sass",
    "vendor/assets/stylesheets/font-awesome-scss.scss",
    "vendor/assets/stylesheets/font-awesome.css.erb"
  ]
  s.homepage = "http://github.com/kristianmandrup/font_awesome-sass-rails"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Font Awesome ready for use with Rails asset pipeline"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1"])
      s.add_runtime_dependency(%q<compass>, [">= 0.11"])
      s.add_runtime_dependency(%q<sass>, [">= 3.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<rails>, [">= 3.1"])
      s.add_dependency(%q<compass>, [">= 0.11"])
      s.add_dependency(%q<sass>, [">= 3.0"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1"])
    s.add_dependency(%q<compass>, [">= 0.11"])
    s.add_dependency(%q<sass>, [">= 3.0"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

